import type { Chat, User } from "./types"

export const initialUsers: User[] = [
  {
    id: "user-1",
    name: "Periskope",
    avatar: "/placeholder.svg?height=40&width=40",
    phone: "+91 99778 44008",
  },
  {
    id: "user-2",
    name: "Roshnag Airtel",
    avatar: "/placeholder.svg?height=40&width=40",
    phone: "+91 63646 47925",
  },
  {
    id: "user-3",
    name: "Test El Centro",
    avatar: "/placeholder.svg?height=40&width=40",
  },
]

export const initialChats: Chat[] = [
  {
    id: "chat-1",
    name: "Test El Centro",
    avatar: "/placeholder.svg?height=40&width=40",
    participants: ["Roshnag Airtel", "Roshnag Jio", "Bharat Kumar Ramesh", "Periskope"],
    preview: "Roshnag: Hello, Ahmadport!",
    lastMessageDate: "04-Feb-25",
    messages: [
      {
        id: "msg-1",
        content: "Hello, Livonia!",
        sender: initialUsers[2],
        timestamp: "08:01",
        status: "read",
      },
      {
        id: "msg-2",
        content: "test el centro",
        sender: initialUsers[0],
        timestamp: "09:49",
        status: "read",
      },
    ],
    tags: ["Demo"],
    phone: "+91 99778 44008",
  },
  {
    id: "chat-2",
    name: "Test Skope Final 5",
    avatar: "/placeholder.svg?height=40&width=40",
    preview: "Support2: This doesn't go on Tuesday...",
    lastMessageDate: "Yesterday",
    messages: [
      {
        id: "msg-1",
        content: "This doesn't go on Tuesday...",
        sender: { id: "user-4", name: "Support2", avatar: "/placeholder.svg?height=40&width=40" },
        timestamp: "11:51",
        status: "read",
      },
    ],
    tags: ["Demo"],
    phone: "+91 99778 44008 +1",
  },
  {
    id: "chat-3",
    name: "Periskope Team Chat",
    avatar: "/placeholder.svg?height=40&width=40",
    preview: "Periskope: Test message",
    lastMessageDate: "28-Feb-25",
    messages: [
      {
        id: "msg-1",
        content: "Test message",
        sender: initialUsers[0],
        timestamp: "11:54",
        status: "read",
      },
      {
        id: "msg-2",
        content: "hello",
        sender: initialUsers[0],
        timestamp: "12:07",
        status: "read",
      },
    ],
    tags: ["Demo", "Internal"],
    phone: "+91 99778 44008 +3",
  },
  {
    id: "chat-4",
    name: "+91 99999 99999",
    avatar: "/placeholder.svg?height=40&width=40",
    preview: "Hi there, I'm Swapnika, Co-Founder of...",
    lastMessageDate: "25-Feb-25",
    messages: [
      {
        id: "msg-1",
        content: "Hi there, I'm Swapnika, Co-Founder of...",
        sender: { id: "user-5", name: "Swapnika", avatar: "/placeholder.svg?height=40&width=40" },
        timestamp: "22-01-2025",
        status: "read",
      },
    ],
    tags: ["Demo", "Signup"],
    phone: "+91 92896 65999 +1",
  },
  {
    id: "chat-5",
    name: "Test Demo17",
    avatar: "/placeholder.svg?height=40&width=40",
    preview: "Rohosen: 123",
    lastMessageDate: "25-Feb-25",
    messages: [
      {
        id: "msg-1",
        content: "123",
        sender: { id: "user-6", name: "Rohosen", avatar: "/placeholder.svg?height=40&width=40" },
        timestamp: "08:01",
        status: "read",
      },
      {
        id: "msg-2",
        content: "Hello, South Euna!",
        sender: initialUsers[1],
        timestamp: "23-01-2025",
        status: "read",
      },
    ],
    tags: ["Content", "Demo"],
    phone: "+91 99778 44008 +1",
  },
  {
    id: "chat-6",
    name: "Testing group",
    avatar: "/placeholder.svg?height=40&width=40",
    preview: "Testing 12345",
    lastMessageDate: "27-Jan-25",
    messages: [
      {
        id: "msg-1",
        content: "Testing 12345",
        sender: { id: "user-7", name: "Tester", avatar: "/placeholder.svg?height=40&width=40" },
        timestamp: "09:49",
        status: "read",
      },
      {
        id: "msg-2",
        content: "testing",
        sender: initialUsers[0],
        timestamp: "09:49",
        status: "read",
      },
    ],
    tags: ["Demo"],
    phone: "+91 92896 65999",
  },
  {
    id: "chat-7",
    name: "Yasin 3",
    avatar: "/placeholder.svg?height=40&width=40",
    preview: "First Bulk Message",
    lastMessageDate: "25-Nov-24",
    messages: [
      {
        id: "msg-1",
        content: "First Bulk Message",
        sender: { id: "user-8", name: "Yasin", avatar: "/placeholder.svg?height=40&width=40" },
        timestamp: "09:49",
        status: "read",
      },
      {
        id: "msg-2",
        content: "CDERT",
        sender: initialUsers[1],
        timestamp: "09:49",
        status: "read",
      },
    ],
    tags: ["Demo", "Dont Send"],
    phone: "+91 99778 44008 +3",
  },
  {
    id: "chat-8",
    name: "Test Skope Final 9473",
    avatar: "/placeholder.svg?height=40&width=40",
    preview: "Heyy",
    lastMessageDate: "01-Jan-25",
    messages: [
      {
        id: "msg-1",
        content: "Heyy",
        sender: { id: "user-9", name: "Tester", avatar: "/placeholder.svg?height=40&width=40" },
        timestamp: "09:49",
        status: "read",
      },
      {
        id: "msg-2",
        content: "testing",
        sender: initialUsers[0],
        timestamp: "09:49",
        status: "read",
      },
    ],
    tags: ["Demo"],
    phone: "+91 99778 44008 +1",
  },
  {
    id: "chat-9",
    name: "Skope Demo",
    avatar: "/placeholder.svg?height=40&width=40",
    preview: "test 123",
    lastMessageDate: "20-Dec-24",
    messages: [
      {
        id: "msg-1",
        content: "test 123",
        sender: { id: "user-10", name: "Demo User", avatar: "/placeholder.svg?height=40&width=40" },
        timestamp: "09:49",
        status: "read",
      },
    ],
    tags: ["Demo"],
    phone: "+91 92896 65999",
  },
  {
    id: "chat-10",
    name: "Test Demo15",
    avatar: "/placeholder.svg?height=40&width=40",
    preview: "test 123",
    lastMessageDate: "20-Dec-24",
    messages: [
      {
        id: "msg-1",
        content: "test 123",
        sender: { id: "user-11", name: "Demo User", avatar: "/placeholder.svg?height=40&width=40" },
        timestamp: "09:49",
        status: "read",
      },
    ],
    tags: ["Demo"],
    phone: "+91 92896 65999",
  },
]

